services:
  web-app:
    build:
      context: .
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: roott
      POSTGRES_PASSWORD: amkmskfla
      POSTGRES_DB: postgres_db
    ports:
      - 5432:5432